{
    'name': 'Hiworth Human resource attendance',
    'description': 'Modifies default attendnace view',
    'author': 'hiworth',
    'depends': [
                'base',
                'product',
                'account',
                'hr_attendance',
                'hr_holidays',
                'hr_payroll',
                'stock'
                ],
    'data': [
        'security/ir.model.access.csv',
        'security/hide_menu.xml',
        # 'security/ir.rule.csv',
        'report/hiworth_hr_leave.xml',
        'report/daily_report.xml',
        'view/hr_contract.xml',
        'view/hiworth_hr_attendance.xml',
        'view/hiworth_hr_leave.xml',
        'view/hr_holidays.xml',
        # 'view/hiworth_hr_attendance_wizard.xml',
        # 'data/defaultdata.xml',
        'view/report_payslip.xml',
        'view/report_payslipdetails.xml',
        'view/hr_employee_view.xml',
        'view/attendance_today.xml',
        'view/res_users.xml',
        'view/attendance_request.xml',
        'view/sequences.xml',
        'view/daily_wages.xml',
       
        'report/worker_wage.xml',
        # 'view/job_title.xml',
        # 'report/id_card.xml',
        'view/employee_attendance_new.xml',
        'view/hr_insurance.xml',
        'view/resigned_employee_view.xml',
        'data/data.xml',
        'report/employee_report.xml',
        'report/insurance_report_view.xml',
        'report/pf_esi_report.xml',
    ]
}
