# import vehicle_odometer_update
import hiworth_fleet
import machinery_fuel
import vehicle_odometer_update
import vehicle_details
import tms_stock_move3
# import hiworth_vehicle_status_report
import workshop_issue_details
import workshop_return_details
import vehicle_tyre
import km_details_config
