import vehicle_diesel_report_wizard_daily
import vehicle_diesel_report_wizard_monthly
import tyre_purchase_register
import tyre_issue_register
import  tyre_removal_register
import vehicle_maintenance_wizard